In [1]:
import pandas as pd # Importing required libraries

In [2]:
df=pd.read_csv(r'D:\MY_DOCUMENT_MAIN_DATA\Desktop\supply chain project\customer_shopping.csv') # Loading dataset

In [3]:
df.isnull().sum() # Handling missing values

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [4]:
df['Review Rating']=df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median())) # Handling missing values

In [5]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [6]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'}) # Standardizing column names

In [7]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [8]:
#creating a age_group
labels=['Young adults','adults','Middle adult','senior']
df['age_group']=pd.qcut(df['age'], q=4,labels=labels)

In [10]:
# creating a purchase_fequency_days

fequency_mapping={
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_fequency_days'] = df['frequency_of_purchases'].map(fequency_mapping)

In [11]:
df[['frequency_of_purchases','purchase_fequency_days']]

     frequency_of_purchases  purchase_fequency_days
0               Fortnightly                      14
1               Fortnightly                      14
2                    Weekly                       7
3                    Weekly                       7
4                  Annually                     365
...                     ...                     ...
3895                 Weekly                       7
3896              Bi-Weekly                      14
3897              Quarterly                      90
3898                 Weekly                       7
3899              Quarterly                      90

[3900 rows x 2 columns]

In [12]:
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [13]:
df=df.drop('promo_code_used', axis=1)

In [14]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_fequency_days'],
      dtype='str')

In [16]:
import mysql.connector
import sqlalchemy

In [22]:
df.to_sql(name='customer_data', con=engine, if_exists='replace', index=False) # Exporting cleaned data to MySQL

3900

In [23]:
frequency_mapping = {
    'Fortnightly' : 14,
    'Weekly':7,
    'Monthly':30,
    'Bi-Weekly': 14,
    'Every 3 Months':90,
    'Quarterly':90,
    'Annually':365,
}
df['purchase_frequency_days']=df['frequency_of_purchases'].map(frequency_mapping)

In [24]:
df[['purchase_frequency_days','frequency_of_purchases']]

      purchase_frequency_days frequency_of_purchases
0                          14            Fortnightly
1                          14            Fortnightly
2                           7                 Weekly
3                           7                 Weekly
4                         365               Annually
...                       ...                    ...
3895                        7                 Weekly
3896                       14              Bi-Weekly
3897                       90              Quarterly
3898                        7                 Weekly
3899                       90              Quarterly

[3900 rows x 2 columns]

In [25]:
df.to_sql(
    name="customer_data",
    con=engine,
    if_exists="replace",   # Exporting cleaned data to MySQL
    index=False
)

3900